### ISSUE TITLE
大佬，能不能改一个能在istoreos上运行的荐片盒子DTS

### ISSUE THREAD

**Issue by hx801217** [zhangn1985/linux-stable#1]
翘首以盼啊

**Comment by avrilnoeme** [comment]
https://github.com/istoreos/istoreos/commit/f4a2c2adb63a6c4e5d982987d1295adeb3551300 
这不是有吗

**Comment by hx801217** [comment]
这是我根据你dts乱七八糟修改的啊。。。。不是原装的，关键我0基础。

**Comment by hx801217** [comment]
或者大佬，能不能请你修一修。。

**Comment by zhangn1985** [comment]
istoreos 的内核版本是5.10，不想弄。
